name: gh:deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
      - name: install
        run: bundle
      - name: pregenerate pages
        run: bundle exec jekyll pagemaster resources --force
      - name: prod build
        run: bundle exec rake reset && bundle exec rake build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          cname: mapping-project.org
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
